import os
import sys
import importlib.util

"""
配置模块初始化
统一从config.py导入配置项，保持向后兼容
"""

_backend_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _backend_dir not in sys.path:
    sys.path.insert(0, _backend_dir)
_config_path = os.path.join(_backend_dir, "config.py")
_spec = importlib.util.spec_from_file_location("config_file", _config_path)
_config_module = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_config_module)
Config = _config_module.Config
config = Config()
CELERY_BROKER_URL = config.CELERY_BROKER_URL
CELERY_RESULT_BACKEND = config.CELERY_RESULT_BACKEND
CELERY_TASK_SERIALIZER = config.CELERY_TASK_SERIALIZER
CELERY_RESULT_SERIALIZER = config.CELERY_RESULT_SERIALIZER
CELERY_ACCEPT_CONTENT = config.CELERY_ACCEPT_CONTENT
CELERY_TIMEZONE = config.CELERY_TIMEZONE
CELERY_ENABLE_UTC = config.CELERY_ENABLE_UTC
CELERY_WORKER_CONCURRENCY = config.CELERY_WORKER_CONCURRENCY
CELERY_WORKER_PREFETCH_MULTIPLIER = config.CELERY_WORKER_PREFETCH_MULTIPLIER
CELERY_TASK_QUEUES = config.CELERY_TASK_QUEUES
CELERY_TASK_ROUTES = config.CELERY_TASK_ROUTES
CELERY_BEAT_SCHEDULE = config.CELERY_BEAT_SCHEDULE
CELERY_BEAT_SCHEDULER = config.CELERY_BEAT_SCHEDULER
CELERY_BEAT_SCHEDULE_FILENAME = config.CELERY_BEAT_SCHEDULE_FILENAME
CELERY_TASK_ACKS_LATE = config.CELERY_TASK_ACKS_LATE
CELERY_TASK_REJECT_ON_WORKER_LOST = config.CELERY_TASK_REJECT_ON_WORKER_LOST
CELERY_TASK_DEFAULT_RETRY_DELAY = config.CELERY_TASK_DEFAULT_RETRY_DELAY
CELERY_TASK_MAX_RETRIES = config.CELERY_TASK_MAX_RETRIES
CELERY_TASK_TIME_LIMIT = config.CELERY_TASK_TIME_LIMIT
CELERY_TASK_SOFT_TIME_LIMIT = config.CELERY_TASK_SOFT_TIME_LIMIT
FLASK_APP = config.FLASK_APP
FLASK_ENV = config.FLASK_ENV
FLASK_DEBUG = config.FLASK_DEBUG
FLASK_SECRET_KEY = config.FLASK_SECRET_KEY
FLASK_HOST = config.FLASK_HOST
FLASK_PORT = config.FLASK_PORT
DATABASE_URI = config.DATABASE_URI
SQLALCHEMY_TRACK_MODIFICATIONS = config.SQLALCHEMY_TRACK_MODIFICATIONS
SQLALCHEMY_ENGINE_OPTIONS = config.SQLALCHEMY_ENGINE_OPTIONS
REDIS_HOST = config.REDIS_HOST
REDIS_PORT = config.REDIS_PORT
REDIS_DB = config.REDIS_DB
REDIS_PASSWORD = config.REDIS_PASSWORD
MQTT_BROKER = config.MQTT_BROKER
MQTT_PORT = config.MQTT_PORT
MQTT_CLIENT_ID = config.MQTT_CLIENT_ID
MQTT_USERNAME = config.MQTT_USERNAME
MQTT_PASSWORD = config.MQTT_PASSWORD
MQTT_SSL = config.MQTT_SSL
MQTT_TIMEOUT = config.MQTT_TIMEOUT
MQTT_KEEPALIVE = config.MQTT_KEEPALIVE
MQTT_TOPIC_PREFIX = config.MQTT_TOPIC_PREFIX
JWT_SECRET_KEY = config.JWT_SECRET_KEY
JWT_ACCESS_TOKEN_EXPIRES = config.JWT_ACCESS_TOKEN_EXPIRES
JWT_REFRESH_TOKEN_EXPIRES = config.JWT_REFRESH_TOKEN_EXPIRES
JWT_ALGORITHM = config.JWT_ALGORITHM
CSRF_SECRET_KEY = config.CSRF_SECRET_KEY
WTF_CSRF_ENABLED = config.WTF_CSRF_ENABLED
WTF_CSRF_TIME_LIMIT = config.WTF_CSRF_TIME_LIMIT
CSRF_TOKEN_LENGTH = config.CSRF_TOKEN_LENGTH
RATE_LIMIT_ENABLED = config.RATE_LIMIT_ENABLED
RATE_LIMIT_PER_MINUTE = config.RATE_LIMIT_PER_MINUTE
RATE_LIMIT_PER_HOUR = config.RATE_LIMIT_PER_HOUR
__all__ = [
    "config",
    "Config",
    "CELERY_BROKER_URL",
    "CELERY_RESULT_BACKEND",
    "CELERY_TASK_SERIALIZER",
    "CELERY_RESULT_SERIALIZER",
    "CELERY_ACCEPT_CONTENT",
    "CELERY_TIMEZONE",
    "CELERY_ENABLE_UTC",
    "CELERY_WORKER_CONCURRENCY",
    "CELERY_WORKER_PREFETCH_MULTIPLIER",
    "CELERY_TASK_QUEUES",
    "CELERY_TASK_ROUTES",
    "CELERY_BEAT_SCHEDULE",
    "CELERY_BEAT_SCHEDULER",
    "CELERY_BEAT_SCHEDULE_FILENAME",
    "CELERY_TASK_ACKS_LATE",
    "CELERY_TASK_REJECT_ON_WORKER_LOST",
    "CELERY_TASK_DEFAULT_RETRY_DELAY",
    "CELERY_TASK_MAX_RETRIES",
    "CELERY_TASK_TIME_LIMIT",
    "CELERY_TASK_SOFT_TIME_LIMIT",
    "FLASK_APP",
    "FLASK_ENV",
    "FLASK_DEBUG",
    "FLASK_SECRET_KEY",
    "FLASK_HOST",
    "FLASK_PORT",
    "DATABASE_URI",
    "SQLALCHEMY_TRACK_MODIFICATIONS",
    "SQLALCHEMY_ENGINE_OPTIONS",
    "REDIS_HOST",
    "REDIS_PORT",
    "REDIS_DB",
    "REDIS_PASSWORD",
    "MQTT_BROKER",
    "MQTT_PORT",
    "MQTT_CLIENT_ID",
    "MQTT_USERNAME",
    "MQTT_PASSWORD",
    "MQTT_SSL",
    "MQTT_TIMEOUT",
    "MQTT_KEEPALIVE",
    "MQTT_TOPIC_PREFIX",
    "JWT_SECRET_KEY",
    "JWT_ACCESS_TOKEN_EXPIRES",
    "JWT_REFRESH_TOKEN_EXPIRES",
    "JWT_ALGORITHM",
    "CSRF_SECRET_KEY",
    "WTF_CSRF_ENABLED",
    "WTF_CSRF_TIME_LIMIT",
    "CSRF_TOKEN_LENGTH",
    "RATE_LIMIT_ENABLED",
    "RATE_LIMIT_PER_MINUTE",
    "RATE_LIMIT_PER_HOUR",
]
