[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short -p no:cacheprovider -p no:locust --timeout=300
filterwarnings =
    ignore::DeprecationWarning
    ignore::FutureWarning

[coverage:run]
source = services, models
omit =
    */__init__.py
    */migrations/*
    */test*

[coverage:report]
show_missing = True
fail_under = 70
