/**
 * 统一权限管理页面 - 整合用户管理、角色管理、权限管理（装配层）
 *
 * 全部 state / effect / loader / handler / 列定义已抽到
 * ./permissionManagement/usePermissionManagementLogic；本文件仅做 props 装配。
 */

import { default as PermissionManagementView } from './permissionManagement/PermissionManagementView';
import { usePermissionManagementLogic } from './permissionManagement/usePermissionManagementLogic';

function PermissionManagement() {
  const {
    loading,
    activeTab,
    setActiveTab,
    admins,
    adminColumns,
    handleCreateAdmin,
    handleEditAdmin,
    handleOpenRoleAssign,
    handleDeleteAdmin,
    classes,
    classColumns,
    handleCreateClass,
    handleEditClass,
    handleDeleteClass,
    roles,
    roleColumns,
    handleOpenCreateRole,
    handleOpenEditRole,
    handleDeleteRole,
    permissionFilter,
    setPermissionFilter,
    groupedPermissions,
    handleOpenCreatePermission,
    handleOpenEditPermission,
    handleDeletePermission,
    permissionLogs,
    logColumns,
    logPage,
    setLogPage,
    logPerPage,
    logTotal,
    showAdminModal,
    setShowAdminModal,
    editingAdmin,
    adminFormData,
    setAdminFormData,
    handleSaveAdmin,
    showClassModal,
    setShowClassModal,
    editingClass,
    classFormData,
    setClassFormData,
    handleSaveClass,
    showRoleModal,
    setShowRoleModal,
    isEditingRole,
    roleFormData,
    setRoleFormData,
    availablePermissions,
    selectedPermissions,
    togglePermission,
    handleSaveRole,
    showPermissionModal,
    setShowPermissionModal,
    isEditingPermission,
    permissionFormData,
    setPermissionFormData,
    handleSavePermission,
    showRoleAssignModal,
    setShowRoleAssignModal,
    selectedAdminForRoles,
    selectedRolesForAdmin,
    toggleAdminRole,
    handleSaveAdminRoles,
    submitting,
    runSubmit,
  } = usePermissionManagementLogic();

  return (
    <PermissionManagementView
      loading={loading}
      activeTab={activeTab}
      setActiveTab={setActiveTab}
      admins={admins}
      adminColumns={adminColumns}
      handleCreateAdmin={handleCreateAdmin}
      handleEditAdmin={handleEditAdmin}
      handleOpenRoleAssign={handleOpenRoleAssign}
      handleDeleteAdmin={handleDeleteAdmin}
      classes={classes}
      classColumns={classColumns}
      handleCreateClass={handleCreateClass}
      handleEditClass={handleEditClass}
      handleDeleteClass={handleDeleteClass}
      roles={roles}
      roleColumns={roleColumns}
      handleOpenCreateRole={handleOpenCreateRole}
      handleOpenEditRole={handleOpenEditRole}
      handleDeleteRole={handleDeleteRole}
      permissionFilter={permissionFilter}
      setPermissionFilter={setPermissionFilter}
      groupedPermissions={groupedPermissions}
      handleOpenCreatePermission={handleOpenCreatePermission}
      handleOpenEditPermission={handleOpenEditPermission}
      handleDeletePermission={handleDeletePermission}
      permissionLogs={permissionLogs}
      logColumns={logColumns}
      logPage={logPage}
      setLogPage={setLogPage}
      logTotal={logTotal}
      logPerPage={logPerPage}
      showAdminModal={showAdminModal}
      setShowAdminModal={setShowAdminModal}
      editingAdmin={editingAdmin}
      adminFormData={adminFormData}
      setAdminFormData={setAdminFormData}
      submitting={submitting}
      handleSaveAdmin={handleSaveAdmin}
      runSubmit={runSubmit}
      showRoleAssignModal={showRoleAssignModal}
      setShowRoleAssignModal={setShowRoleAssignModal}
      selectedAdminForRoles={selectedAdminForRoles}
      selectedRolesForAdmin={selectedRolesForAdmin}
      toggleAdminRole={toggleAdminRole}
      handleSaveAdminRoles={handleSaveAdminRoles}
      showClassModal={showClassModal}
      setShowClassModal={setShowClassModal}
      editingClass={editingClass}
      classFormData={classFormData}
      setClassFormData={setClassFormData}
      handleSaveClass={handleSaveClass}
      showRoleModal={showRoleModal}
      setShowRoleModal={setShowRoleModal}
      isEditingRole={isEditingRole}
      roleFormData={roleFormData}
      setRoleFormData={setRoleFormData}
      availablePermissions={availablePermissions}
      selectedPermissions={selectedPermissions}
      togglePermission={togglePermission}
      handleSaveRole={handleSaveRole}
      showPermissionModal={showPermissionModal}
      setShowPermissionModal={setShowPermissionModal}
      isEditingPermission={isEditingPermission}
      permissionFormData={permissionFormData}
      setPermissionFormData={setPermissionFormData}
      handleSavePermission={handleSavePermission}
    />
  );
}

export default PermissionManagement;
